#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CODEX_HOME="${CODEX_OBSIDIAN_MEMORY_CODEX_HOME:-$HOME/.codex}"
INSTALL_ROOT="${CODEX_OBSIDIAN_MEMORY_INSTALL_ROOT:-$CODEX_HOME/hooks/obsidian-memory-starter}"
RUNTIME_HOOKS_DIR="${INSTALL_ROOT}/hooks"
PROJECTS_LOCAL="${CODEX_OBSIDIAN_MEMORY_PROJECTS_FILE:-$INSTALL_ROOT/config/projects.local.json}"
HOOKS_JSON="${CODEX_HOME}/hooks.json"

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

pass() {
  printf 'PASS: %s\n' "$1"
}

[[ -f "${HOOKS_JSON}" ]] || fail "hooks.json not found at ${HOOKS_JSON}"
[[ -f "${RUNTIME_HOOKS_DIR}/session_start.py" ]] || fail "missing installed session_start.py"
[[ -f "${RUNTIME_HOOKS_DIR}/user_prompt_submit.py" ]] || fail "missing installed user_prompt_submit.py"
[[ -f "${RUNTIME_HOOKS_DIR}/stop.py" ]] || fail "missing installed stop.py"
[[ -f "${PROJECTS_LOCAL}" ]] || fail "missing projects.local.json at ${PROJECTS_LOCAL}"

export HOOKS_JSON
export INSTALL_ROOT
export PROJECTS_LOCAL

python3 <<'PY' || fail "hooks.json does not contain all three managed hook commands"
import json
import os
from pathlib import Path

hooks_json = Path(os.environ["HOOKS_JSON"])
install_root = os.environ["INSTALL_ROOT"]
payload = json.loads(hooks_json.read_text())
expected = {
    "SessionStart": f"{install_root}/hooks/session_start.py",
    "UserPromptSubmit": f"{install_root}/hooks/user_prompt_submit.py",
    "Stop": f"{install_root}/hooks/stop.py",
}

for event_name, needle in expected.items():
    entries = payload.get("hooks", {}).get(event_name, [])
    if not any(needle in hook.get("command", "") for entry in entries for hook in entry.get("hooks", [])):
        raise SystemExit(1)
PY
pass "hooks.json contains managed hook commands"

TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/codex-obsidian-memory-verify.XXXXXX")"
trap 'rm -rf "${TMP_ROOT}"' EXIT

TEMP_CODEX_HOME="${TMP_ROOT}/codex_home"
TEMP_VAULT_ROOT="${TMP_ROOT}/vault"
TEMP_PROJECTS_LOCAL="${TMP_ROOT}/projects.local.json"
TEMP_TRANSCRIPT="${TMP_ROOT}/transcript.jsonl"
SESSION_ID="verify-session-001"

mkdir -p "${TEMP_CODEX_HOME}" "${TEMP_VAULT_ROOT}"
cp "${PROJECTS_LOCAL}" "${TEMP_PROJECTS_LOCAL}"

export TEMP_CODEX_HOME
export TEMP_VAULT_ROOT
export TEMP_PROJECTS_LOCAL
export TEMP_TRANSCRIPT
export SESSION_ID

python3 <<'PY'
import json
import os
from pathlib import Path

projects_path = Path(os.environ["TEMP_PROJECTS_LOCAL"])
vault_root = Path(os.environ["TEMP_VAULT_ROOT"])
payload = json.loads(projects_path.read_text())

for project in payload.get("projects", []):
    project["workspace_hints"] = ["__verify_workspace__"]

    note_relative = str(project.get("project_note", "")).strip()
    if note_relative:
        note_path = vault_root / note_relative
        note_path.parent.mkdir(parents=True, exist_ok=True)
        if not note_path.exists():
            title = str(project.get("project_id", "Project")).replace("-", " ").title()
            note_path.write_text(
                f"# {title}\n\n"
                "## Goal\n\n"
                "Verification placeholder project note.\n\n"
                "## Current State\n\n"
                "- Generated by verify_install.sh\n"
            )

    for rule_relative in project.get("related_rules", []):
        rule_path = vault_root / str(rule_relative)
        rule_path.parent.mkdir(parents=True, exist_ok=True)
        if not rule_path.exists():
            rule_path.write_text(
                "# Verification Rule\n\n"
                "- Short verification rule note.\n"
            )

projects_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")

first_project = (payload.get("projects") or [{}])[0]
keywords = [str(item).strip() for item in first_project.get("keywords", []) if str(item).strip()]
tokens = keywords[:3] or ["memory", "obsidian", "hooks"]
prompt = "Please verify " + " ".join(tokens) + " write timing rules and hook behavior."
Path(os.environ["TEMP_TRANSCRIPT"]).write_text(
    json.dumps(
        {
            "type": "event_msg",
            "payload": {
                "type": "user_message",
                "message": prompt,
            },
        },
        ensure_ascii=False,
    )
    + "\n"
)
print(prompt)
PY

VERIFY_PROMPT="$(python3 <<'PY'
import json
import os
from pathlib import Path

payload = json.loads(Path(os.environ["TEMP_PROJECTS_LOCAL"]).read_text())
first_project = (payload.get("projects") or [{}])[0]
keywords = [str(item).strip() for item in first_project.get("keywords", []) if str(item).strip()]
tokens = keywords[:3] or ["memory", "obsidian", "hooks"]
print("Please verify " + " ".join(tokens) + " write timing rules and hook behavior.")
PY
)"

USER_OUTPUT="$(
  printf '%s' "{\"session_id\":\"${SESSION_ID}\",\"cwd\":\"__verify_workspace__\",\"prompt\":\"${VERIFY_PROMPT}\",\"agent_id\":\"\"}" \
    | env \
        CODEX_OBSIDIAN_MEMORY_REPO_ROOT="${INSTALL_ROOT}" \
        CODEX_OBSIDIAN_MEMORY_CODEX_HOME="${TEMP_CODEX_HOME}" \
        CODEX_OBSIDIAN_MEMORY_VAULT_ROOT="${TEMP_VAULT_ROOT}" \
        CODEX_OBSIDIAN_MEMORY_PROJECTS_FILE="${TEMP_PROJECTS_LOCAL}" \
        python3 "${RUNTIME_HOOKS_DIR}/user_prompt_submit.py"
)"

SESSION_OUTPUT="$(
  printf '%s' '{"cwd":"__verify_workspace__","agent_id":""}' \
    | env \
        CODEX_OBSIDIAN_MEMORY_REPO_ROOT="${INSTALL_ROOT}" \
        CODEX_OBSIDIAN_MEMORY_CODEX_HOME="${TEMP_CODEX_HOME}" \
        CODEX_OBSIDIAN_MEMORY_VAULT_ROOT="${TEMP_VAULT_ROOT}" \
        CODEX_OBSIDIAN_MEMORY_PROJECTS_FILE="${TEMP_PROJECTS_LOCAL}" \
        python3 "${RUNTIME_HOOKS_DIR}/session_start.py"
)"

printf '%s' "{\"session_id\":\"${SESSION_ID}\",\"cwd\":\"__verify_workspace__\",\"transcript_path\":\"${TEMP_TRANSCRIPT}\",\"last_assistant_message\":\"Verified memory hook behavior and episode write timing.\",\"agent_id\":\"\"}" \
  | env \
      CODEX_OBSIDIAN_MEMORY_REPO_ROOT="${INSTALL_ROOT}" \
      CODEX_OBSIDIAN_MEMORY_CODEX_HOME="${TEMP_CODEX_HOME}" \
      CODEX_OBSIDIAN_MEMORY_VAULT_ROOT="${TEMP_VAULT_ROOT}" \
      CODEX_OBSIDIAN_MEMORY_PROJECTS_FILE="${TEMP_PROJECTS_LOCAL}" \
      python3 "${RUNTIME_HOOKS_DIR}/stop.py" >/dev/null

[[ "${USER_OUTPUT}" == *'"hookEventName": "UserPromptSubmit"'* ]] || fail "UserPromptSubmit did not emit hook output"
[[ "${SESSION_OUTPUT}" == *'"hookEventName": "SessionStart"'* ]] || fail "SessionStart did not emit hook output"

python3 <<'PY' || fail "functional verification did not produce expected notes and state"
import json
import os
from pathlib import Path

vault_root = Path(os.environ["TEMP_VAULT_ROOT"])
codex_home = Path(os.environ["TEMP_CODEX_HOME"])
session_id = os.environ["SESSION_ID"]

ultra_short_files = sorted((vault_root / "episodes" / "ultra_short").glob("*.md"))
episode_files = sorted((vault_root / "episodes").glob("*.md"))
episode_files = [path for path in episode_files if path.name.lower() != "readme.md"]
state_path = codex_home / "hooks" / "state" / f"{session_id}.json"

if not ultra_short_files:
    raise SystemExit(1)
if not episode_files:
    raise SystemExit(1)
if not state_path.exists():
    raise SystemExit(1)

ultra_short_text = ultra_short_files[0].read_text()
episode_text = episode_files[0].read_text()

if 'prompt="' not in ultra_short_text:
    raise SystemExit(1)
if "- " not in episode_text:
    raise SystemExit(1)
PY

pass "functional hook simulation succeeded in isolated verification sandbox"
pass "nose-picking install check completed"
